version: '3'
services:
    image_to_video.web:
        build:
            context: ./frontend
            target: frontend
        image: image_to_video/frontend
        ports:
            - '5000:5000'
        volumes:
            - 'image_to_video_store:/app/uploads'
        networks:
            - image_to_video_net
    image_to_video.repo:
        build:
            context: ./repository
            target: repository
        image: image_to_video/repository
        ports:
            - '5001:5001'
        volumes:
            - 'image_to_video_store:/app/uploads'
        networks:
            - image_to_video_net
    image_to_video.builder:
        build:
            context: ./videobuilder
            target: videobuilder
        image: image_to_video/videobuilder
        ports:
            - '5002:5002'
        volumes:
            - 'image_to_video_store:/app/uploads'
        networks:
            - image_to_video_net
networks:
    image_to_video_net:
        driver: bridge
volumes:
    image_to_video_store:
        driver: local
